# Generated by Django 2.2.10 on 2020-02-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('kr', 'Korean'), ('en', 'English')], max_length=3),
        ),
    ]
