# Generated by Django 2.2.10 on 2020-02-24 11:21

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_bookedday'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookedday',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reservation',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
    ]
