# Generated by Django 2.2.9 on 2020-01-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200124_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='accuracy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
