# Generated by Django 2.2.9 on 2020-01-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200121_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='instant_hook',
            new_name='instant_book',
        ),
    ]
