# Generated by Django 2.2.10 on 2020-02-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20200214_1645'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['-updated'], name='rooms_photo_updated_26447f_idx'),
        ),
    ]
