# Generated by Django 2.2.10 on 2020-02-24 11:21

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20200215_1458'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='amenity',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='facility',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='houserule',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='photo',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='room',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='roomtype',
            managers=[
                ('objects', core.managers.CustomModelManager()),
            ],
        ),
    ]
